//! Differential check: Rust `extract_features` vs the Python reference.
//!
//! Usage: `cargo run -p personal-taoli-uzi --example features_diff -- <ref_dir>`
//! where `<ref_dir>` holds `raw_data.json`; the expected feature vector is
//! `crates/uzi/tools/out/ref_features.json` (generated by
//! `tools/compile_panel_data.py`).

use std::collections::BTreeMap;

use serde_json::Value;

fn main() -> anyhow::Result<()> {
    let dir = std::env::args()
        .nth(1)
        .unwrap_or_else(|| panic!("usage: features_diff <ref_dir>"));
    let raw: Value =
        serde_json::from_str(&std::fs::read_to_string(format!("{dir}/raw_data.json"))?)?;
    let expected: BTreeMap<String, Value> = serde_json::from_str(&std::fs::read_to_string(
        "crates/uzi/tools/out/ref_features.json",
    )?)?;

    let data = personal_taoli_uzi::panel_data()?;
    let actual = personal_taoli_uzi::features::extract_features(&raw, &data.feature_tables);
    let actual = actual
        .as_object()
        .ok_or_else(|| anyhow::anyhow!("extract_features did not return an object"))?;

    let mut missing = Vec::new();
    let mut extra = Vec::new();
    let mut wrong = Vec::new();

    for (k, want) in &expected {
        match actual.get(k) {
            None => missing.push(k.clone()),
            Some(got) => {
                if !close(want, got) {
                    wrong.push(format!("{k}: expected {want}, got {got}"));
                }
            }
        }
    }
    for k in actual.keys() {
        if !expected.contains_key(k) {
            extra.push(k.clone());
        }
    }

    println!("python keys : {}", expected.len());
    println!("rust keys   : {}", actual.len());
    println!();

    if missing.is_empty() && extra.is_empty() && wrong.is_empty() {
        println!("IDENTICAL — {} features matched", expected.len());
        return Ok(());
    }
    if !missing.is_empty() {
        println!("MISSING ({}): {}", missing.len(), missing.join(", "));
    }
    if !extra.is_empty() {
        println!("EXTRA ({}): {}", extra.len(), extra.join(", "));
    }
    if !wrong.is_empty() {
        println!("WRONG ({}):", wrong.len());
        for w in wrong.iter().take(25) {
            println!("  {w}");
        }
    }
    anyhow::bail!(
        "{} missing, {} extra, {} wrong",
        missing.len(),
        extra.len(),
        wrong.len()
    );
}

/// Numeric comparison with a tolerance; exact match for everything else.
fn close(want: &Value, got: &Value) -> bool {
    match (want, got) {
        (Value::Number(a), Value::Number(b)) => match (a.as_f64(), b.as_f64()) {
            (Some(x), Some(y)) => (x - y).abs() <= 1e-9 * x.abs().max(1.0),
            _ => a == b,
        },
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(p, q)| close(p, q))
        }
        _ => want == got,
    }
}
